/* NOTE: This is an autogenerated file; please do not edit. */

import * as helloWorldStories from './components/HelloWorld.stories'

const modules = [
  helloWorldStories,
];

export default modules;