/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { StoryComponents } from "@stories/stories-common";
export namespace Components {
    interface StoriesApp {
        /**
          * Stories
         */
        "stories": StoryComponents;
    }
    interface StoriesLayout {
    }
    interface StoriesNavigator {
    }
    interface StoriesViewer {
    }
}
declare global {
    interface HTMLStoriesAppElement extends Components.StoriesApp, HTMLStencilElement {
    }
    var HTMLStoriesAppElement: {
        prototype: HTMLStoriesAppElement;
        new (): HTMLStoriesAppElement;
    };
    interface HTMLStoriesLayoutElement extends Components.StoriesLayout, HTMLStencilElement {
    }
    var HTMLStoriesLayoutElement: {
        prototype: HTMLStoriesLayoutElement;
        new (): HTMLStoriesLayoutElement;
    };
    interface HTMLStoriesNavigatorElement extends Components.StoriesNavigator, HTMLStencilElement {
    }
    var HTMLStoriesNavigatorElement: {
        prototype: HTMLStoriesNavigatorElement;
        new (): HTMLStoriesNavigatorElement;
    };
    interface HTMLStoriesViewerElement extends Components.StoriesViewer, HTMLStencilElement {
    }
    var HTMLStoriesViewerElement: {
        prototype: HTMLStoriesViewerElement;
        new (): HTMLStoriesViewerElement;
    };
    interface HTMLElementTagNameMap {
        "stories-app": HTMLStoriesAppElement;
        "stories-layout": HTMLStoriesLayoutElement;
        "stories-navigator": HTMLStoriesNavigatorElement;
        "stories-viewer": HTMLStoriesViewerElement;
    }
}
declare namespace LocalJSX {
    interface StoriesApp {
        "onStory"?: (event: CustomEvent<any>) => void;
        /**
          * Stories
         */
        "stories"?: StoryComponents;
    }
    interface StoriesLayout {
    }
    interface StoriesNavigator {
    }
    interface StoriesViewer {
    }
    interface IntrinsicElements {
        "stories-app": StoriesApp;
        "stories-layout": StoriesLayout;
        "stories-navigator": StoriesNavigator;
        "stories-viewer": StoriesViewer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stories-app": LocalJSX.StoriesApp & JSXBase.HTMLAttributes<HTMLStoriesAppElement>;
            "stories-layout": LocalJSX.StoriesLayout & JSXBase.HTMLAttributes<HTMLStoriesLayoutElement>;
            "stories-navigator": LocalJSX.StoriesNavigator & JSXBase.HTMLAttributes<HTMLStoriesNavigatorElement>;
            "stories-viewer": LocalJSX.StoriesViewer & JSXBase.HTMLAttributes<HTMLStoriesViewerElement>;
        }
    }
}
