/* NOTE: This is an autogenerated file; please do not edit. */

import * as buttonComponentStories from '../app/button/button.component.stories'

const modules = [
  buttonComponentStories,
];

export default modules;