
import * as d from './proxies';

export const DIRECTIVES = [
  d.StrAddonActions,
  d.StrAddonControls,
  d.StrAddons,
  d.StrApp,
  d.StrBadge,
  d.StrButton,
  d.StrCheckbox,
  d.StrCol,
  d.StrDropdown,
  d.StrFooter,
  d.StrGrid,
  d.StrGroup,
  d.StrIcon,
  d.StrInput,
  d.StrLabel,
  d.StrMenu,
  d.StrMenuDivider,
  d.StrMenuItem,
  d.StrMenuLabel,
  d.StrPreview,
  d.StrRadio,
  d.StrRadioGroup,
  d.StrRouter,
  d.StrRow,
  d.StrSearchbar,
  d.StrSelect,
  d.StrSidebar,
  d.StrSpinner,
  d.StrSplitPane,
  d.StrTab,
  d.StrTabBar,
  d.StrTabButton,
  d.StrTabs,
  d.StrTag,
  d.StrTextarea,
  d.StrToolBar,
  d.StrToolButton,
  d.StrToolZoom,
  d.StrZoom
];
