/* NOTE: This is an autogenerated file; please do not edit. */

import * as viewStories from '../components/View.stories';
import * as buttonStories from '../components/Button.stories';

const modules = [
  viewStories,
  buttonStories,
];

export default modules;